include:
  - path: ./server/compose.yml
    env_file:
      - ./server/.env.development
  - path: infra/keycloak/compose.yml

services:
  backend:
    command: ["npm", "run", "dev"]
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"