services:
  backend:
    command: ["npm", "run", "dev"]
    env_file:
      - ./server/.env.development
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  redis:
    image: "redis:8.6.0-alpine"
    expose:
      - "6379"
    command: [ "redis-server" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 20s

  migrate:
    image: "amacneil/dbmate"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./server/.env.development
    volumes:
      - ./server/db/migrations:/db/migrations
    command: [ "up" ]

  db:
    image: "mysql:latest"
    expose:
      - "3306"
    env_file:
      - ./server/.env.development
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      interval: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
  mailhog:
    image: "mailhog/mailhog"
    ports:
      - "1025:1025"
      - "8025:8025"



volumes:
  db-data:

