-- migrate:up
CREATE TABLE roles(
    role_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    role_name VARCHAR(64) NOT NULL UNIQUE ,
    role_description varchar(500) NOT NULL,
    created_at NOT NULL TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at NOT NULL TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
);


-- migrate:down
DROP TABLE IF EXISTS roles;
