-- migrate:up
CREATE TABLE families(
    family_id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    family_uuid BINARY(16) NOT NULL UNIQUE,
    family_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);

-- migrate:down
DROP TABLE IF EXISTS families;