-- migrate:up
CREATE TABLE permissions(
    permission_id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    permission_name VARCHAR(64) NOT NULL UNIQUE,
    permission_description VARCHAR(500) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- migrate:down
DROP TABLE IF EXISTS permissions;