services:
  nginx:
    build:
      context: ../..
      dockerfile: ./infra/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    depends_on:
      keycloak:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
    networks:
      default:
        aliases:
            - app.localhost
            - auth.localhost