
upstream oauth2_proxy {
    server oauth2proxy:4180;
}


server {
    listen 80 ;
    server_name app.localhost;
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    add_header_inherit merge;
    add_header X-Frame-Options DENY always;
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    sub_filter_once off;
    sub_filter '<script ' '<script nonce="$request_id" ';
    add_header Content-Security-Policy "default-src 'self'; script-src 'nonce-$request_id' 'strict-dynamic'; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'none'" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /index.html{
        add_header Cache-Control "private, no-cache, no-store, max-age=0, must-revalidate" always;
    }


    location ^~ /_expo/static/ {
        add_header Cache-Control "public, max-age=31536000, immutable" always;
    }





}

