/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownInputParams; } | { pathname: `/chat_bot/chatbotui`; params?: Router.UnknownInputParams; } | { pathname: `/daily_check_in/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/daily_check_in/daily`; params?: Router.UnknownInputParams; } | { pathname: `/daily_check_in/progress`; params?: Router.UnknownInputParams; } | { pathname: `/home_screen/events`; params?: Router.UnknownInputParams; } | { pathname: `/home_screen/home`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/quiz_list`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/GAD7/gad_7Disclaimer`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/GAD7/gad_7Questions`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/GAD7/gad_7Results`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/PHQ9/phq_9Disclaimer`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/PHQ9/phq_9Questions`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/PHQ9/phq_9Results`; params?: Router.UnknownInputParams; } | { pathname: `/resources/resource`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownOutputParams; } | { pathname: `/chat_bot/chatbotui`; params?: Router.UnknownOutputParams; } | { pathname: `/daily_check_in/calendar`; params?: Router.UnknownOutputParams; } | { pathname: `/daily_check_in/daily`; params?: Router.UnknownOutputParams; } | { pathname: `/daily_check_in/progress`; params?: Router.UnknownOutputParams; } | { pathname: `/home_screen/events`; params?: Router.UnknownOutputParams; } | { pathname: `/home_screen/home`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/quizzes/quiz_list`; params?: Router.UnknownOutputParams; } | { pathname: `/quizzes/GAD7/gad_7Disclaimer`; params?: Router.UnknownOutputParams; } | { pathname: `/quizzes/GAD7/gad_7Questions`; params?: Router.UnknownOutputParams; } | { pathname: `/quizzes/GAD7/gad_7Results`; params?: Router.UnknownOutputParams; } | { pathname: `/quizzes/PHQ9/phq_9Disclaimer`; params?: Router.UnknownOutputParams; } | { pathname: `/quizzes/PHQ9/phq_9Questions`; params?: Router.UnknownOutputParams; } | { pathname: `/quizzes/PHQ9/phq_9Results`; params?: Router.UnknownOutputParams; } | { pathname: `/resources/resource`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/authentication/login${`?${string}` | `#${string}` | ''}` | `/chat_bot/chatbotui${`?${string}` | `#${string}` | ''}` | `/daily_check_in/calendar${`?${string}` | `#${string}` | ''}` | `/daily_check_in/daily${`?${string}` | `#${string}` | ''}` | `/daily_check_in/progress${`?${string}` | `#${string}` | ''}` | `/home_screen/events${`?${string}` | `#${string}` | ''}` | `/home_screen/home${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/quizzes/quiz_list${`?${string}` | `#${string}` | ''}` | `/quizzes/GAD7/gad_7Disclaimer${`?${string}` | `#${string}` | ''}` | `/quizzes/GAD7/gad_7Questions${`?${string}` | `#${string}` | ''}` | `/quizzes/GAD7/gad_7Results${`?${string}` | `#${string}` | ''}` | `/quizzes/PHQ9/phq_9Disclaimer${`?${string}` | `#${string}` | ''}` | `/quizzes/PHQ9/phq_9Questions${`?${string}` | `#${string}` | ''}` | `/quizzes/PHQ9/phq_9Results${`?${string}` | `#${string}` | ''}` | `/resources/resource${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/authentication/login`; params?: Router.UnknownInputParams; } | { pathname: `/chat_bot/chatbotui`; params?: Router.UnknownInputParams; } | { pathname: `/daily_check_in/calendar`; params?: Router.UnknownInputParams; } | { pathname: `/daily_check_in/daily`; params?: Router.UnknownInputParams; } | { pathname: `/daily_check_in/progress`; params?: Router.UnknownInputParams; } | { pathname: `/home_screen/events`; params?: Router.UnknownInputParams; } | { pathname: `/home_screen/home`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/quiz_list`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/GAD7/gad_7Disclaimer`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/GAD7/gad_7Questions`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/GAD7/gad_7Results`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/PHQ9/phq_9Disclaimer`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/PHQ9/phq_9Questions`; params?: Router.UnknownInputParams; } | { pathname: `/quizzes/PHQ9/phq_9Results`; params?: Router.UnknownInputParams; } | { pathname: `/resources/resource`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
